name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Lint podspec
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Xcode version
        uses: maxim-lobanov/setup-xcode@v1.2.1
        with: 
          xcode-version: '11.6'
      - name: Lint Podspec
        run: pod lib lint --use-libraries --allow-warnings --verbose   

  build:
    name: Build and Test 
    runs-on: macos-latest
    strategy:
      matrix:
        scheme: [OTAcceleratorCore, OTAnnotationSample, OTTextChatSample]
        destination: ['platform=iOS Simulator,name=iPhone 14,OS=16.1']
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache Pods
        uses: actions/cache@v2
        with:
          path: Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-
      - name: Setup Xcode version
        uses: maxim-lobanov/setup-xcode@v1.2.1
        with: 
          xcode-version: '14.1'
      - name: Cocoapods
        run: pod update
      - name: Test ${{ matrix.scheme }}
        run: xcodebuild clean build test -workspace OTAcceleratorCore.xcworkspace -scheme ${{ matrix.scheme }} -destination "${{ matrix.destination }}" -configuration Debug || exit 1