name: Lint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Lint podspec
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Xcode version
        uses: maxim-lobanov/setup-xcode@v1.2.1
        with: 
          xcode-version: '11.6'
      - name: Lint Podspec
        run: pod lib lint --use-libraries --allow-warnings --verbose
